import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { LeftNav } from "./ui/navbar/left-nav";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Spicy Slow Chat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="grid grid-cols-8 gap-4 ">
          <div className="col-span-1 h-screen bg-slate-600 text-white mr-2 ">
            <LeftNav />
          </div>
          <div className="col-span-6">{children}</div>
        </div>
      </body>
    </html>
  );
}
