import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { LeftNav } from "./ui-components/navbar/left-nav";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Spicy Slow Chat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="grid grid-cols-10 gap-4 ">
          <div className="col-span-1 bg-blue-100">
            <LeftNav />
          </div>
          <div className="col-span-8">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut
            perspiciatis exercitationem ducimus natus eaque perferendis corporis
            a commodi! Consectetur illum quia quibusdam deserunt soluta
            temporibus in id? Debitis laudantium ducimus asperiores nihil nobis
            sed distinctio fuga adipisci modi. Est, dolorum blanditiis!
            Praesentium, repellat iure expedita suscipit ut aspernatur
            consequuntur labore possimus! Eligendi reprehenderit qui sit minus
            expedita ipsam accusantium explicabo.
          </div>
        </div>

        {children}
      </body>
    </html>
  );
}
